version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=delivery
    expose:
      - 27017

  delivery:
    build: delivery
    expose:
      - 5000
    volumes:
      - delivery_static:/delivery/static

  nginx:
    build: ./nginx
    volumes:
      - delivery_static:/delivery/static
    ports:
      - 1337:80
    depends_on:
      - delivery

volumes:
  delivery_static:
